= HotRod tester
Álvaro López Medina <alopezme@redhat.com>
v1.0, 2020-12
// Create TOC wherever needed
:toc: macro
:sectanchors:
:sectnumlevels: 2
:sectnums:
:source-highlighter: pygments
:imagesdir: images
// Start: Enable admonition icons
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
:icons: font
endif::[]
// End: Enable admonition icons
// Create the Table of contents here
toc::[]


TIP: This project is based on the work of @drhelius at https://github.com/drhelius/hotrod-tester

This project contains some varied examples that showcase useful configurations of RHDG Hot Rod client: Basic cache operations, queries, indexing, transactions, etc.





== Running the application

You can run this application locally or on OCP. These are the steps.


WARNING: The following sections assume that you have a Red Hat Data Grid 8.1 server cluster running either on OCP or locally. For more information about configuring your cluster, check the following https://github.com/alvarolop/rhdg8-server[link].

WARNING: This application needs at least one cache created on the cluster in order to launch without errors. Create a cache as explained in the <<../README.adoc#22-cache-configuration-using-the-rest-api,Cache Configuration section>> of the main Readme of this repository:

[source, bash]
----
CACHE_NAME="indexed-cache"
curl -X POST -k -u developer:developer -H "Content-Type: application/json" ${RHDG_URL}/rest/v2/caches/${CACHE_NAME} --data-binary "@../caches/distributed-indexed.json"
----


=== Running the client locally

Developing new functionality directly on OCP can be quite cumbersome due to the long time it takes to build a new version of the image after pushing changes. Therefore, the best way to test your application is running your application locally:

The default configuration of the application is prepared for the DG clusters created on Openshift using the operator (With SSL configured by default). To run it locally, specify a custom `application.properties` path:

[source, bash]
----
mvn clean package 
java -jar target/hotrod-tester-1.0.0.jar --spring.config.location=src/main/resources/application-local.properties
----

or, in one line:
[source, bash]
----
mvn clean spring-boot:run -Dspring-boot.run.arguments=--spring.config.location=src/main/resources/application-local.properties
----


=== Running the client on Openshift

Deploying your client application on OCP requires to create several Openshift objects. Therefore, we are going to define some common variables that will be used from now onwards:

[source, bash]
----
export app_name=rhdg8-hotrod-tester
export namespace=rhdg8
export datagrid_cluster=rhdg
export git_repo=https://github.com/alvarolop/rhdg8-client.git
export git_context=hotrod-tester
----


First, create two Config Maps that will store your application configuration:
[source, bash]
----
oc create configmap ${app_name}-file-config --from-file=./${git_context}/src/main/resources/application.properties -n $namespace
oc create configmap ${app_name}-logback-config --from-file=./${git_context}/src/main/resources/logback-spring.xml -n $namespace
----


Second, use an Openshift template to create your Openshift resources. There are two templates inside the `templates` folder:

* `rhdg-client.yaml`: Template that creates all the necessary OCP objects for your application. 
* `rhdg-client-ssl.yaml`: The same template but including the `.pem` file generated by the operator inside the client's container.

This is the command to apply the template on your cluster:
[source, bash]
----
oc process -f templates/rhdg-client-ssl.yaml -p APPLICATION_NAME=$app_name -p GIT_REPOSITORY=$git_repo -p GIT_CONTEXT_DIR=$git_context -p APP_NAMESPACE=$namespace -p RHDG_CLUSTER_NAME=$datagrid_cluster | oc apply -f -
----



== The application components


This application may be used to test many different features included in the Java implementation of Hot Rod protocol. All the tests and application logic is exposed via three REST endpoints:

* `api/basic`: Basic methods to test cache behavior: put, get, remove, restart, etc.
* `api/queries`: Methods to interact with an indexed cache to perform queries, bulk removes based on the result of queries and interact with cache indexes.
* `api/transaction`: Basic methods to test transactions.


=== Environment set up

If your client application is running on OCP, define these environment variables to simplify the following commands:
[source, bash]
----
APP_NAMESPACE="rhdg8"
APP_NAME="rhdg8-hotrod-tester"
APP_URL=$(oc get route ${APP_NAME} -n ${APP_NAMESPACE} -o template='https://{{.spec.host}}')
CACHE_NAME="distributed-01"
----

On the contrary, if your application is running locally, define these environment variables to simplify the following commands:
[source, bash]
----
APP_URL="http://localhost:8080"
CACHE_NAME="distributed-02"
----


=== Basic features

Basic operations:

[source, bash]
----
# Put bytes from 0 to 49
curl -k -G -X PUT "${APP_URL}/api/basic/cache/${CACHE_NAME}/bytes" -d size=1024 -d entries=50

# Put strings from 100 to 149
curl -k -G -X PUT "${APP_URL}/api/basic/cache/${CACHE_NAME}/string" -d minkey=100 -d entries=50

# Get Bulk from 100 to 149
curl -k -G -X GET "${APP_URL}/api/basic/cache/${CACHE_NAME}/bulk" -d minkey=100 -d entries=50

# Get byte entry 0
curl -k -G -X GET "${APP_URL}/api/basic/cache/${CACHE_NAME}/byte" -d key=0 -d show=true

# Get string entry 101
curl -k -G -X GET "${APP_URL}/api/basic/cache/${CACHE_NAME}/string" -d key=101 -d show=true

# Get keys
curl -k -G -X GET "${APP_URL}/api/basic/cache/${CACHE_NAME}/keys"

# Remove entries (From 10 to 110)
curl -k -G -X DELETE "${APP_URL}/api/basic/cache/${CACHE_NAME}" -d minkey=10 -d entries=100
----






==== Basic features performed several times

Follow these steps:
[source, bash]
----
# Put 50 times
for i in {1..50}; do echo "Time $i"; curl -k -X PUT -G "${CLIENT_URL}/api/basic/cache/${CACHE_NAME}/byte" -d size=41943040 -d entries=1; done

# Get 50 times
for i in {1..50}; do echo "Time $i"; curl -k -X GET -G "${CLIENT_URL}/api/basic/cache/${CACHE_NAME}/byte" -d key=0 -d show=true; done

# Perform gets in parallel (10 threads)
for ((i=1;i<=10;i++)); do curl -k -X GET -G "${CLIENT_URL}/api/basic/cache/${CACHE_NAME}/string" -d entries=1000 -d minkey=40000 -d async=true; done
----




=== Queries and indexes

TIP: These features are not tested against the cache `$CACHE_NAME`, but against a cache named `indexed-cache`. It is possible to modify the cache you are going to use in the `application.properties` file and restart the client application.





=== Transactions

ERROR: Work in progress








== ANNEX A: Debugging inside the pod

It is possible to enter into a pod and execute commands to check cache cluster stats:


[source, bash]
----
# Enter into the pod
$ oc rsh rhdg73-4-server-0

# Use the cli command line
$ /opt/datagrid/bin/cli.sh -c

# Check attributes of a cache
/subsystem=datagrid-infinispan/cache-container=clustered/distributed-cache=default:read-resource(include-runtime=true)
----


