# spring:
#   application:
#     name: datagrid-tester
#   profiles:
#     active: ${SPRING_PROFILES_ACTIVE:local}

logging:
  level:
    root: error
    com.alopezme: debug
    org.springframework.web: info

management:
  endpoints:
    web:
      exposure:
        include: "*"
    
