version: '3'

services:

  datagrid1:
    container_name: datagrid1
    image: registry.redhat.io/datagrid/datagrid-8-rhel8:1.0
    hostname: datagrid1
    environment:
      USER: developer
      PASS: developer
    ports:
      - 11222:11222
      - 2157:2157
      - 7800:7800
      - 11221:11221
      - 45700:45700
      - 57600:57600
    networks:
      - cluster
   

  datagrid2:
    container_name: datagrid2
    image: registry.redhat.io/datagrid/datagrid-8-rhel8:1.0
    hostname: datagrid2
    environment:
      USER: developer
      PASS: developer
    ports:
      - 11223:11222
    networks:
      - cluster
    depends_on:
      - datagrid1

    
  # ping-test:    
  #   container_name: busybox
  #   image: busybox
  #   hostname: busybox
  #   command: ping datagrid1
  #   networks:
  #   - cluster

  
networks:
  cluster:
    driver: bridge