apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: rhdg8-client
  annotations:
    description: Template to deploy a Java client application to connecto to a RHDG cluster on OCP.
    tags: infinispan,datagrid,java,springboot
    iconClass: icon-rh-openjdk
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
labels:
  template: rhdg8-client
objects:

  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: monitor-${APP_NAME}
      namespace: ${APP_NAMESPACE}
    spec:
      endpoints:
        - interval: 10s
          targetPort: 8080
          path: /api/actuator/prometheus
          scheme: http
      namespaceSelector:
        matchNames:
          - ${APP_NAMESPACE}
      selector:
        matchLabels:
          app: ${APP_NAME}

parameters:
- name: APP_NAME
  description: "The name of the application."
  required: true
- name: APP_NAMESPACE
  description: "The namespace of the application."
  required: true
