apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: rhdg8-client
  annotations:
    description: Template to deploy a Java client application to connecto to a RHDG cluster on OCP.
    tags: infinispan,datagrid,java,springboot
    iconClass: icon-rh-openjdk
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
labels:
  template: rhdg8-client
objects:

  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      labels:
        app: ${APP_NAME}
      name: ${APP_NAME}
      namespace: ${APP_NAMESPACE}
    spec:
      lookupPolicy:
        local: true

  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        app: ${APP_NAME}
      name: ${APP_NAME}
      namespace: ${APP_NAMESPACE}
    spec:
      nodeSelector:
      output:
        to:
          kind: ImageStreamTag
          name: ${APP_NAME}:latest
      postCommit: {}
      resources: {}
      runPolicy: Serial
      source:
        git:
          uri: ${GIT_REPOSITORY}
          ref: ${GIT_BRANCH}
        type: Git
      strategy:
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: ubi8-openjdk-11:1.3
            namespace: openshift
        type: Source
      failedBuildsHistoryLimit: 1
      successfulBuildsHistoryLimit: 0
      triggers:
      - type: ConfigChange
      - type: ImageChange

parameters:
- name: APP_NAME
  description: "The name of the application."
  required: true
- name: APP_NAMESPACE
  description: "The namespace of the application."
  required: true
- name: GIT_REPOSITORY
  description: "The git repository of the application."
  required: true
- name: GIT_BRANCH
  description: "The git branch of the application."
  required: true
  value: "main"
