{
 "title": "RHDG 8 Client",
 "tags": [
  "middleware",
  "monitoring",
  "rhdg8"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "pod", "label": "pod", "query": { "query": "label_values(cache_reset,pod)" } },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(cache_reset,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cache Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cache Gets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cache_gets_total" }
   ]
  },
  {
   "title": "Cache Puts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cache_puts_total" }
   ]
  },
  {
   "title": "Cache Gets Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cache_gets_latency" }
   ]
  },
  {
   "title": "Cache Puts Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cache_puts_latency" }
   ]
  },
  { "title": "JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  { "title": "OCP 4 Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "Used {{pod}}"
    },
    {
     "expr": "sum(kube_pod_resource_request{resource='cpu',pod=~\"$pod\",namespace=~\"$namespace\"}) BY (pod, namespace)",
     "legendFormat": "Request {{pod}}"
    },
    {
     "expr": "sum(kube_pod_resource_limit{resource='cpu',pod=~\"$pod\",namespace=~\"$namespace\"}) BY (pod, namespace)",
     "legendFormat": "Limit {{pod}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$pod\",namespace=~\"$namespace\",container='',}) BY (pod, namespace)",
     "legendFormat": "Used {{pod}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate({__name__=~\"container_network_receive_bytes_total\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Rx {{pod}}"
    },
    {
     "expr": "- rate({__name__=~\"container_network_transmit_bytes_total\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Tx {{pod}}"
    }
   ]
  }
 ]
}