apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: {{ .Values.application.name }}
  name: {{ .Values.application.name }}
  namespace: {{ .Values.application.namespace }}
spec:
  nodeSelector:
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.image.name }}:{{ .Values.image.tag }}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: {{ .Values.git.repository }}
      ref: {{ .Values.git.branch }}
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: ubi8-openjdk-11:1.3
        namespace: openshift
    type: Source
  failedBuildsHistoryLimit: 1
  successfulBuildsHistoryLimit: 0
  triggers:
    - type: ConfigChange
    - type: ImageChange